### ISSUE TITLE
Control which actors can actually use ViNo

### ISSUE THREAD

**Issue by TatianaKat** [cswendrowski/FoundryVTT-ViNo-Public#15]
Hi there,

My apologies if this is already answered elsewhere, I wasn't able to find it so far. Is there any way at the moment to control which actors can or cannot be affected by ViNo? It seems to basically affect everyone at the moment and I'd really like it to basically only apply to specific actors (e.g NPCs only, or specific NPCs). 

Thanks in advance!

**Comment by cswendrowski** [comment]
There is currently not a toggle, I have added this request to the project board, thanks!
